#!/bin/bash

wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb

sudo dpkg -i erlang-solutions_1.0_all.deb

sudo apt-get update

sudo apt-get install erlang erlang-nox

echo 'deb http://www.rabbitmq.com/debian/ testing main' | sudo tee /etc/apt/sources.list.d/rabbitmq.list

wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | sudo apt-key add -

sudo apt-get update

sudo apt-get install rabbitmq-server

sudo update-rc.d rabbitmq-server defaults

sudo service rabbitmq-server start

#sudo service rabbitmq-server stop

#sudo rabbitmqctl add_user admin password 

#sudo rabbitmqctl set_user_tags admin administrator

#sudo rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"

#sudo rabbitmq-plugins enable rabbitmq_management
